[build]
command = "pip install -r requirements.txt && npm install && npm run build"

[build.environment]
PIP_CACHE_DIR = "/opt/build/cache/pip"

[context.production]
command = "pip install -r requirements.txt && npm run build"

